### 1. Register a new user
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "testuser@gmail.com",
  "password": "mySecurePassword123",
  "firstName": "John",
  "lastName": "Doe"
}

### 2. Login to get your JWT Token
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "email": "admin@furniflux.com",
  "password": "AdminMaster2026!"
}
### 2. Post product (Form-Data Version)
POST http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBmdXJuaWZsdXguY29tIiwicm9sZSI6IkFETUlOIiwiZmlyc3ROYW1lIjoiRnVybmlGbHV4IiwiaWF0IjoxNzgxODUxNTUzLCJleHAiOjE3ODE5Mzc5NTN9.4jh1nGrBlGXcLeYz9sKltN36jVftYooBXjkrR2APxMI

Content-Type: multipart/form-data; boundary=boundary-string

--boundary-string
Content-Disposition: form-data; name="product"
Content-Type: application/json

{
  "name": "Ekena Minimalist Chair",
  "description": "A sleek, clean oak wood dining chair perfect for modern homes.",
  "price": 149.99,
  "stockQuantity": 10
}


--boundary-string--


### 3. Place an Order (Copy the token from step 2 response)
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlckBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJmaXJzdE5hbWUiOiJKb2huIiwiaWF0IjoxNzgxODEyNDM4LCJleHAiOjE3ODE4OTg4Mzh9.ux49NKislXsXnkzXTid2wRp7lqBLcpYlpGKQxu-NQqw

{
  "items": [
    {
      "productId": 1,
      "quantity": 2
    }
  ]
}